version: "3.7"
services:
  server:
    build: 
      context: .
      dockerfile: ./Dockerfile.server
    image: irods-server:4.2.10
    networks:
      - network
    ports:
      - "1247:1247"
  client:
    build: 
      context: .
      dockerfile: ./Dockerfile.client
    image: irods-client:4.2.10
    networks:
      - network
    environment:
      IRODS_HOST: server 
      IRODS_PORT : 1247
      IRODS_USER: rods 
      IRODS_PASSWORD: rods
      IRODS_ZONE: tempZone
    depends_on:
      - server
networks:
  network: {}
