name: irods CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Docker compose to  start server and client containers
      run: docker-compose up -d
    - name: Run unit tests on client container
      run: |
        sleep 10
        sudo docker exec irods_client_1 py.test /irods_client_tests.py -v --junitxml="result.xml"
        if [ $? -eq 0 ]; then echo "Unit tests failed"; exit 1; fi
